FROM golang:1.12.0 AS builder
RUN mkdir /app
ADD . /app
WORKDIR /app
RUN go build -o main .

FROM golang
WORKDIR /root/
COPY --from=builder /app/hello-world.go .
EXPOSE 8081
CMD ["go", "run", "hello-world.go"]
